version: '3'
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: lhsadmin
      POSTGRES_USER: lhsroot
      POSTGRES_DB: lhsDB
      PDDATA: /var/lib/postgressql/data
    volumes:
      - ./pgdata:/var/lib/postgressql/data

  pgadmin:
    container_name: pd-admin
    image: dpage/pgadmin4:6.15
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lhs.org
      PGADMIN_DEFAULT_PASSWORD: lhsadmin123
      PGADMIN_LISTEN_PORT: 3500
    ports:
      - "3500:3500"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    links:
      - "postgres:pgsql-server"